import {StyleSheet} from 'react-native';

export const globalstyles = StyleSheet.create({
  FormMainView: {
    height: '100%',
    backgroundColor: '#add8e6',
    padding: 20,
    marginBottom: 100,
  },
  FormView: {
    backgroundColor: '#fff',
    borderRadius: 5,
    paddingTop: 20,
    marginBottom: 150,
  },
  FormUpperHeading: {
    paddingLeft: 20,
    paddingRight: 20,
  },
  FormFirstHeading: {
    fontSize: 22,
    fontWeight: '700',
    textAlign: 'center',
  },
  FormSubHeading: {
    fontSize: 18,
    fontWeight: '500',
    textAlign: 'center',
  },
  FormSection: {
    borderRadius: 4,
    borderColor: '#746f6f24',
    borderWidth: 1,
    paddingTop: 20,
    margin: 20,
  },
  StepFormSection: {
    borderRadius: 4,
    borderColor: '#746f6f24',
    borderWidth: 1,
    margin: 20,
    padding: 20,
  },
  FormSubSection: {
    borderRadius: 4,
    borderColor: '#746f6f24',
    borderWidth: 1,
    padding: 15,
    margin: 15,
    marginTop: 5,
  },
  FormHeading: {
    fontSize: 30,
    fontWeight: 'bold',
    color: '#000',
    textAlign: 'center',
    marginBottom: 20,
  },
  FormInput: {
    borderBottomColor: '#0000001a',
    borderBottomWidth: 1,
    height: 46,
    fontSize: 20,
    marginBottom: 20,
    borderRadius: 4,
    color: '#000',
    fontWeight: '400',
  },
  NextStepBtn: {
    backgroundColor: '#483d8b',
    width: 100,
    height: 46,
    borderRadius: 12,
    marginBottom: 30,
    marginLeft: 10,
  },
  NextStepText: {
    color: '#fff',
    fontSize: 16,
    textAlign: 'center',
    padding: 10,
  },
  PreviousStepBtn: {
    backgroundColor: '#616161',
    width: 100,
    height: 46,
    borderRadius: 12,
    marginBottom: 30,
    marginRight: 10,
  },
  PreviousStepText: {
    color: '#fff',
    fontSize: 16,
    textAlign: 'center',
    padding: 10,
  },
  CheckView: {
    flexDirection: 'row',
    marginBottom: 20,
  },
  CheckText: {
    color: '#575454de',
    fontSize: 16,
    paddingRight: 20,
    marginLeft: -10,
    marginTop: 3,
  },
  InfoText: {
    color: '#9E9E9E',
    marginBottom: 20,
    fontSize: 16,
  },
  RequiredText: {
    textAlign: 'right',
    fontSize: 14,
    fontWeight: '700',
    color: '#ff4f37',
    paddingRight: 20,
  },
  Required: {
    fontSize: 14,
    fontWeight: '600',
    color: '#ff4f37',
  },
  FormLabel: {
    fontSize: 15,
    fontWeight: '400',
    color: '#000',
  },
  UncheckSelectIcon: {
    width: 20,
    height: 20,
    borderRadius: 4,
    backgroundColor: '#fff',
    borderColor: '#575454de',
    borderWidth: 1,
    padding: 2,
    marginLeft: -20,
    marginTop: -10,
  },
  checkSelectIcon: {
    width: 20,
    height: 20,
    borderRadius: 4,
    backgroundColor: '#4169e1',
    padding: 2,
    marginLeft: -20,
    marginTop: -10,
  },
  DropdownView: {
    flexDirection: 'row',
  },
  DropdownStyle: {
    width: 200,
    color: '#fff',
    backgroundColor: '#9E9E9E',
    borderColor: '#9E9E9E',
    borderRadius: 4,
    height: 30,
    marginTop: 10,
    marginBottom: 20,
  },
  DropdownFormStyle: {
    width: 150,
    color: '#fff',
    backgroundColor: '#9E9E9E',
    borderColor: '#9E9E9E',
    borderRadius: 4,
    height: 30,
    marginTop: 10,
    marginBottom: 20,
    marginRight: 10,
  },
  DropdownYearStyle: {
    width: 120,
    color: '#fff',
    backgroundColor: '#9E9E9E',
    borderColor: '#9E9E9E',
    borderRadius: 4,
    height: 30,
    marginTop: 10,
    marginBottom: 20,
    marginLeft: 10,
  },
  DropdownExpStyle: {
    width: 200,
    color: '#fff',
    backgroundColor: '#9E9E9E',
    borderColor: '#9E9E9E',
    borderRadius: 4,
    height: 30,
    marginTop: 10,
    marginBottom: 20,
    marginLeft: 10,
  },
  DropdownPicker: {
    color: '#fff',
    bottom: 12,
  },
  FeesHeading: {
    fontSize: 30,
    fontWeight: 'bold',
    color: '#000',
    marginBottom: 20,
  },
});
